### ISSUE TITLE
Feature: User can see inventory

### ISSUE THREAD

**Issue by jonathan-byun** [jonathan-byun/my-kitchen#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can see stocked ingredients.

User can see stocked ingredients.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on inventory to see listed ingredients by category.

User can click on inventory to see listed ingredients by category.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/39111205/163234533-bc1eb705-7fd4-4aad-97f9-a0bc52a27923.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to designed schema on dbdesigner.

### ☁️ Server

- [x] Update index.js to include get request to database for items joined to stocked items
- [x] Update index.js to include a patch request to update inventory quantity in stored items 

### ⚡ Client

- [x] Create a component to hold displayed inventory
- [x] create a component to show add modal on click
- [x] Create a component to display inventory item with current quantity and name
- [x] Create a component to be a category button to display items with that category
- [x] Update a component on click of - and + buttons to change current inventory number
- [x] Update a component to show category highlighted for current category
- [x] Update a component to show only sub components that are within selected category on change

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
