### ISSUE TITLE
Feature: User can add new inventory item

### ISSUE THREAD

**Issue by jonathan-byun** [jonathan-byun/my-kitchen#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a new item to the inventory specifying quantity, unit measurement, and category.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click add button on inventory page to pop up a modal for adding, input name, quantity, and category.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/39111205/163239205-f147603d-0a7e-45f8-b702-6f943544ff61.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include post request to create a new entry to items and stocked items
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to have all input information for adding new item
- [x] Update component to highlight category on click and have it as state
- [x] Update component to show food and quantity inputs on change
- [x] Update component to switch unit measurement on click of unit
- [x] Update component to disappear on submit

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
